export type NotificationType =
	| "TICKET_ASSIGNED"
	| "TICKET_UNASSIGNED"
	| "TICKET_COMMENT_CREATED"
	| "TICKET_STATUS_CHANGED"
	| "TICKET_DETAILS_UPDATED"
	| "TICKET_PRIORITY_CHANGED"
	| "TICKET_SUBTICKET_ADDED"
	| "TICKET_ARCHIVED"
	| "TICKET_RESTORED"
	| "TICKET_DELETED"
	| "PROJECT_USER_ADDED"
	| "PROJECT_USER_ROLE_CHANGED"
	| "PROJECT_USER_REMOVED"
	| "USER_CREATED"
	| "USER_USERNAME_CHANGED"
	| "USER_PASSWORD_CHANGED"
	| "USER_WORKSPACE_ROLE_CHANGED"
	| "USER_DEACTIVATED"
	| "USER_REACTIVATED";

export type Notification = {
	id: number;
	type: NotificationType;
	payload: Record<string, unknown>;
	createdAt: string;
	readAt: string | null;
};
