package de.fallstudie.minerva.backend.activity;

public enum ActivityEventType {
	PROJECT_CREATED, PROJECT_USER_ADDED, PROJECT_USER_ROLE_CHANGED, TICKET_CREATED, TICKET_COMMENT_CREATED, TICKET_STATUS_CHANGED, TICKET_DETAILS_UPDATED, TICKET_PRIORITY_CHANGED, TICKET_ASSIGNEE_CHANGED, TICKET_SUBTICKET_ADDED
}
