package de.fallstudie.minerva.backend.activity;

public enum ActivityEventType {
	TICKET_CREATED, TICKET_COMMENT_CREATED, TICKET_STATUS_CHANGED, TICKET_DETAILS_UPDATED, TICKET_PRIORITY_CHANGED, TICKET_ASSIGNEE_CHANGED, TICKET_SUBTICKET_ADDED
}
